version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "npm"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "actions"
